import { COUNTRY_BY_NAME } from "@/lib/countries";

export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  EE: ["Tallinn", "Tartu", "Narva", "Pärnu", "Kohtla-Järve", "Viljandi", "Rakvere"],
  LV: ["Riga", "Daugavpils", "Liepāja", "Jelgava", "Jūrmala", "Ventspils", "Rēzekne"],
  LT: ["Vilnius", "Kaunas", "Klaipėda", "Šiauliai", "Panevėžys", "Alytus", "Marijampolė"],
  FI: ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku", "Jyväskylä", "Lahti", "Kuopio"],
  SE: ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Linköping", "Örebro", "Västerås", "Helsingborg"],
  NO: ["Oslo", "Bergen", "Stavanger", "Trondheim", "Drammen", "Fredrikstad", "Kristiansand"],
  DK: ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg", "Randers", "Kolding"],
  IS: ["Reykjavik", "Akureyri", "Hafnarfjörður"],
  RU: ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan", "Nizhny Novgorod", "Chelyabinsk", "Samara", "Rostov-on-Don", "Ufa", "Krasnoyarsk", "Perm", "Voronezh", "Volgograd", "Krasnodar", "Saratov"],
  UA: ["Kyiv", "Kharkiv", "Odessa", "Dnipro", "Donetsk", "Zaporizhzhia", "Lviv", "Kryvyi Rih", "Mykolaiv", "Mariupol"],
  BY: ["Minsk", "Gomel", "Mogilev", "Vitebsk", "Grodno", "Brest", "Babruysk"],
  PL: ["Warsaw", "Kraków", "Łódź", "Wrocław", "Poznań", "Gdańsk", "Szczecin", "Bydgoszcz", "Lublin", "Białystok", "Katowice"],
  CZ: ["Prague", "Brno", "Ostrava", "Plzeň", "Liberec", "Olomouc", "Ústí nad Labem", "České Budějovice"],
  SK: ["Bratislava", "Košice", "Prešov", "Žilina", "Nitra", "Banská Bystrica"],
  HU: ["Budapest", "Debrecen", "Miskolc", "Szeged", "Pécs", "Győr", "Nyíregyháza"],
  RO: ["Bucharest", "Cluj-Napoca", "Timișoara", "Iași", "Constanța", "Craiova", "Brașov", "Galați"],
  BG: ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse", "Stara Zagora", "Pleven"],
  MD: ["Chișinău", "Tiraspol", "Bălți", "Bender"],
  DE: ["Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt", "Stuttgart", "Düsseldorf", "Leipzig", "Dortmund", "Essen", "Bremen", "Dresden", "Hannover", "Nuremberg", "Duisburg", "Bochum", "Wuppertal"],
  AT: ["Vienna", "Graz", "Linz", "Salzburg", "Innsbruck", "Klagenfurt", "Wels"],
  CH: ["Zurich", "Geneva", "Basel", "Bern", "Lausanne", "Winterthur", "St. Gallen", "Lugano"],
  NL: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven", "Tilburg", "Groningen", "Almere", "Breda", "Nijmegen"],
  BE: ["Brussels", "Antwerp", "Ghent", "Charleroi", "Liège", "Bruges", "Namur", "Leuven"],
  LU: ["Luxembourg City", "Esch-sur-Alzette", "Differdange"],
  FR: ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg", "Montpellier", "Bordeaux", "Lille", "Rennes", "Reims", "Le Havre", "Saint-Étienne", "Toulon"],
  MC: ["Monaco"],
  "GB-ENG": ["London", "Birmingham", "Manchester", "Leeds", "Sheffield", "Liverpool", "Bristol", "Newcastle", "Nottingham", "Leicester", "Coventry", "Bradford", "Stoke-on-Trent", "Southampton"],
  "GB-SCT": ["Edinburgh", "Glasgow", "Aberdeen", "Dundee", "Inverness", "Perth"],
  "GB-WLS": ["Cardiff", "Swansea", "Newport", "Wrexham"],
  "GB-NIR": ["Belfast", "Londonderry", "Lisburn", "Newry"],
  IE: ["Dublin", "Cork", "Limerick", "Galway", "Waterford", "Drogheda"],
  ES: ["Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza", "Málaga", "Murcia", "Palma", "Las Palmas", "Bilbao", "Alicante", "Córdoba", "Valladolid", "Vigo", "Gijón", "Granada", "A Coruña"],
  PT: ["Lisbon", "Porto", "Braga", "Setúbal", "Coimbra", "Funchal", "Almada", "Amadora"],
  IT: ["Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Bologna", "Florence", "Bari", "Catania", "Venice", "Verona", "Messina", "Padua", "Trieste"],
  GR: ["Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa", "Volos", "Ioannina", "Chania"],
  HR: ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar", "Slavonski Brod", "Pula"],
  SI: ["Ljubljana", "Maribor", "Celje", "Kranj", "Koper", "Velenje"],
  RS: ["Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica", "Zrenjanin"],
  BA: ["Sarajevo", "Banja Luka", "Mostar", "Tuzla", "Zenica"],
  ME: ["Podgorica", "Nikšić", "Herceg Novi", "Bar"],
  MK: ["Skopje", "Bitola", "Kumanovo", "Tetovo", "Ohrid"],
  AL: ["Tirana", "Durrës", "Vlorë", "Shkodër", "Fier", "Elbasan"],
  XK: ["Pristina", "Prizren", "Peja", "Mitrovica"],
  CY: ["Nicosia", "Limassol", "Larnaca", "Paphos", "Famagusta"],
  MT: ["Valletta", "Birkirkara", "Qormi", "Mosta", "Żabbar"],
  GE: ["Tbilisi", "Kutaisi", "Batumi", "Rustavi", "Zugdidi"],
  AM: ["Yerevan", "Gyumri", "Vanadzor", "Vagharshapat"],
  AZ: ["Baku", "Ganja", "Sumqayit", "Mingəçevir", "Lankaran"],
  KZ: ["Almaty", "Nur-Sultan", "Shymkent", "Aktobe", "Karaganda", "Taraz", "Pavlodar"],
  UZ: ["Tashkent", "Samarkand", "Namangan", "Andijan", "Nukus", "Bukhara", "Fergana"],
  TM: ["Ashgabat", "Türkmenabat", "Mary", "Balkanabat"],
  KG: ["Bishkek", "Osh", "Jalal-Abad", "Karakol"],
  TJ: ["Dushanbe", "Khujand", "Kulob", "Qŭrghonteppa"],
  TR: ["Istanbul", "Ankara", "Izmir", "Bursa", "Adana", "Gaziantep", "Konya", "Antalya", "Kayseri", "Mersin", "Diyarbakır", "Samsun", "Denizli", "Şanlıurfa"],
  IL: ["Jerusalem", "Tel Aviv", "Haifa", "Rishon LeZion", "Petah Tikva", "Ashdod", "Netanya", "Be'er Sheva"],
  SA: ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam", "Khobar", "Taif", "Tabuk"],
  AE: ["Dubai", "Abu Dhabi", "Sharjah", "Al Ain", "Ajman", "Ras Al Khaimah"],
  QA: ["Doha", "Al Rayyan", "Umm Salal", "Al Wakrah"],
  IR: ["Tehran", "Mashhad", "Isfahan", "Karaj", "Tabriz", "Shiraz", "Ahvaz"],
  IQ: ["Baghdad", "Basra", "Mosul", "Erbil", "Kirkuk", "Najaf"],
  JO: ["Amman", "Zarqa", "Irbid", "Aqaba", "Russeifa"],
  LB: ["Beirut", "Tripoli", "Sidon", "Tyre", "Jounieh"],
  US: ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose", "Austin", "Jacksonville", "Fort Worth", "Columbus", "Charlotte", "Indianapolis", "San Francisco", "Seattle", "Denver", "Nashville", "Miami", "Atlanta", "Minneapolis", "Boston", "Portland"],
  CA: ["Toronto", "Montreal", "Vancouver", "Calgary", "Edmonton", "Ottawa", "Winnipeg", "Quebec City", "Hamilton", "Kitchener"],
  MX: ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "León", "Juárez", "Zapopan", "Mérida", "Cancún"],
  BR: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Fortaleza", "Belo Horizonte", "Manaus", "Curitiba", "Recife", "Porto Alegre", "Belém", "Goiânia"],
  AR: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "La Plata", "Tucumán", "Mar del Plata", "Salta", "Santa Fe"],
  CO: ["Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena", "Cúcuta", "Bucaramanga"],
  CL: ["Santiago", "Valparaíso", "Concepción", "La Serena", "Antofagasta", "Temuco", "Rancagua", "Iquique"],
  PE: ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Iquitos", "Piura", "Cusco"],
  UY: ["Montevideo", "Salto", "Paysandú", "Las Piedras"],
  VE: ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Maracay"],
  EC: ["Quito", "Guayaquil", "Cuenca", "Santo Domingo", "Ambato"],
  BO: ["La Paz", "Santa Cruz", "Cochabamba", "Oruro", "Sucre", "Potosí"],
  NG: ["Lagos", "Kano", "Ibadan", "Abuja", "Port Harcourt", "Benin City", "Kaduna", "Maiduguri"],
  GH: ["Accra", "Kumasi", "Tamale", "Sekondi-Takoradi", "Sunyani"],
  SN: ["Dakar", "Touba", "Thiès", "Kaolack", "Ziguinchor"],
  CI: ["Abidjan", "Bouaké", "Daloa", "San-Pédro", "Yamoussoukro"],
  CM: ["Yaoundé", "Douala", "Bafoussam", "Garoua", "Bamenda"],
  MA: ["Casablanca", "Rabat", "Fes", "Salé", "Marrakech", "Agadir", "Tangier", "Meknes"],
  EG: ["Cairo", "Alexandria", "Giza", "Shubra El-Kheima", "Port Said", "Suez", "Mansoura", "Luxor", "Aswan"],
  ZA: ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth", "Bloemfontein", "East London"],
  TN: ["Tunis", "Sfax", "Sousse", "Kairouan", "Bizerte", "Gabès"],
  DZ: ["Algiers", "Oran", "Constantine", "Annaba", "Blida", "Sétif", "Sidi Bel Abbès"],
  CN: ["Shanghai", "Beijing", "Chongqing", "Guangzhou", "Shenzhen", "Tianjin", "Wuhan", "Dongguan", "Chengdu", "Nanjing", "Xi'an", "Hangzhou", "Shenyang", "Harbin"],
  JP: ["Tokyo", "Yokohama", "Osaka", "Nagoya", "Sapporo", "Kobe", "Kyoto", "Fukuoka", "Kawasaki", "Saitama"],
  KR: ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Suwon", "Ulsan"],
  IN: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Ahmedabad", "Chennai", "Kolkata", "Surat", "Pune", "Jaipur", "Lucknow", "Kanpur", "Nagpur", "Indore", "Thane"],
  AU: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Gold Coast", "Newcastle", "Canberra", "Hobart", "Darwin"],
  NZ: ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga", "Napier-Hastings", "Dunedin"],
  OTHER: [],
};

// Get cities for a country (by country name or code)
export function getCitiesForCountry(countryNameOrCode: string): string[] {
  if (CITIES_BY_COUNTRY[countryNameOrCode]) {
    return CITIES_BY_COUNTRY[countryNameOrCode];
  }
  const country = COUNTRY_BY_NAME.get(countryNameOrCode);
  if (country && CITIES_BY_COUNTRY[country.code]) {
    return CITIES_BY_COUNTRY[country.code];
  }
  return [];
}
